
spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false&useTimezone=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: Daniel_2068668459
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

server:
  port: 8080
